### ISSUE TITLE
github相比于原来开发模式的显著优点探讨

### ISSUE THREAD

**Issue by WhateverYoung** [liangjg/Transplant#3]
原有开发模式
========
- 服务器的远端版本库
- 个人的本地版本库
- 结合real论坛
- 开发过程多为，单人独立大型功能，数月合并推送合并分支一次（和理想情况相差甚远）
- 沟通少，无代码审查，造成代码质量差

github的显著优点
========
- 离校人员方便的参与到项目中
- 合并审核功能
  * 该功能即，其他开发者申请合并的时候，可以由其他人审查代码，提供反馈，修改合适后合并，而且过程一直都是可以追踪的
  * 原本的开发模式，是否也可以容纳这个功能呢？ 显然可以，某种程度上，我觉得直接和相关人士到会议室面对面讨论，实际效率要高一些
  * 所以问题的关键，是建立起一种开发模式，或者是规法：大型功能开发，先开发原型，然后细化到一个个小功能点，多重构多设计，一步一步合并，每次合并均有代码审查，迭代式合并，即pr
- 版本库简洁明了
  * 不知道是不是我理解有误，为什么会简洁明了，是团队的版本库中始终只有三个分支这个意思？ 但是只要完成一次PR，这个开发者的版本历史不就合并进来了吗，倒是可以人为的进行删减。但是如果是这样的话，我们原有的开发模式一样可以进行删减，所以未能明白该优点，还希望得到进一步解释

**Comment by WhateverYoung** [comment]
讨论不是不支持该项工作，而是通过对比找出一些最根本性的问题，然后在规范制定过程中予以体现

**Comment by liangjg** [comment]
欢迎讨论。
关于合并审核功能：第一，单独的git进行审查代码，理论上也可行，但从事实、实际开发过程来看，基本没有先例，为什么呢？或者想象一下，从明天开始这么做推行难度有多大？
我认为这体现了平台、制度（就是你说的模式/规范）的重要性。若想要大家沿着正确的路走，那就需要把路设计好。Github提供了这个平台，是很好的基础。规范当然也很重要，也是这一次摸索的重点。

版本库简洁，主要指分支Branch的简化，现有的模式，所有人的分支都推送到在版本库里，而实际上每一项功能可能有很多分支（试错、多方案），导致版本库分支臃、杂，而且很多不必要的commit也都存在于主版本库，github的pull request功能可以屏蔽不少这种无用分支。

**Comment by WhateverYoung** [comment]
讲真，平台搭建好之后，还是有很长一段路要走，毕竟使用平台的前提是大家要付出额外的努力来学习这套东西，而学习完成后，如何养成一个良好的习惯，还是需要在探索中不断完善规范，才能做到的。

**Comment by liangjg** [comment]
万事开头难，总要迈出这一步吧

**Comment by liangjg** [comment]
问题，会一直存在，也不会一下子解决。但不管结果怎样，从我个人来说，我至少可以借这个机会学习一些新东西。大概如此吧。

**Comment by WhateverYoung** [comment]
感觉楼上有点偏题

**Comment by liangjg** [comment]
所以你的point是development workflow了？我很赞同非常重要。Github可以说提供了最好的平台。感兴趣可以看一下下面这篇文章：

http://openresearchsoftware.metajnl.com/articles/10.5334/jors.bx/#
